'blank_issues_enabled': true
'contact_links':
  - 'about': >
        Please check TrustTunnel Flutter Client README for more useful information about our product
    'name': 'README'
    'url': 'https://github.com/TrustTunnel/TrustTunnelFlutterClient/blob/master/README.md'
