---
version: 2
deployment:
  name: iOS • TrustTunnel • Nightly

deployment-permissions:
- users:
    - bamboo-bot
  permissions:
    - view
- users:
    - a.ivanov
    - k.gorynin
  permissions:
    - view
    - edit

default-environment-permissions:
  - users:
      - bamboo-bot
    permissions:
      - view
      - deploy
  - users:
      - a.ivanov
      - k.gorynin
    permissions:
      - view
      - edit
      - deploy
